# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: archlinux:latest
variables:
  GIT_SUBMODULE_STRATEGY: recursive
before_script:
  - pacman -Sy install pandoc texlive-most make
pages:
  stage: deploy
  script:
    - cd cv
    - make
    - cd ..
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master